### PR TITLE
Minor update in exporting module

### PR DESCRIPTION
**Pull request by alperb**
Using ES6's module.exports method can be more useful.

### CODE REVIEW

**Comment by eralpsahin** [comment]
Hey, thanks for the PR.

I don't know a lot about JS modules but after searching for a little while it seems `export` is the ES6 way of exporting and `module.exports` is CommonJS.

Why can `module.exports` be useful?

**Comment by alperb** [comment]
Since a lot of developer tend to assign a variable while requiring a package like: `const mysu = require(“mysu-api”)`, module.exports lets us to assign it directly to the variable. Thats why I thought it would be more useful.

**Comment by eralpsahin** [comment]
`export default` also supposedly does the same thing but I was just testing and it seems like with the current one, `require()` returns the module wrapped in an object with `default` field.

With your change it returns the module itself.

**Comment by alperb** [comment]
It’s interesting, I wasn’t able to access `MySU` class while exporting module with `export default`, had to change it to `module.exports` may be causing because of my environment.

**Pull request merged**
